### PR TITLE
Remove deprecated metamask events

### PR DESCRIPTION
**Pull request by EdsonAlcala**
Hello, I'm seeing warning about deprecated events and I fix a couple of them.

1) Removed networkChanged listener (https://docs.metamask.io/guide/ethereum-provider.html#networkchanged-deprecated)

2) Rename close to disconnect (https://docs.metamask.io/guide/ethereum-provider.html#close-deprecated)

Thanks

### CODE REVIEW

**Comment by jhirn** [comment]
Would love to see this and related metamask warnings get merged.

**Comment by greg-nagy** [comment]
@jhirn I have used this in the past to change dependency package code in my projects: https://www.npmjs.com/package/patch-package

This might help you out if you still have the issues.

**Comment by jhirn** [comment]
Thx @greg-nagy. I might give it a show but this repo seems to be heading away from web3-react library all together which will be a very good thing.

**Comment by khanhhaquang** [comment]
How is the status of this update ?

**Comment by ahmadina** [comment]
How is the status of this update ?

**Comment by adshodgson** [comment]
I can't wait for this ...Switching to Avax defaults to chainId 1 this will solve so many issues for me.

**Comment by NoahZinsmeister** [comment]
hi all - sorry for the non-response on this. i'm going to be focusing development efforts on the v8 of this library going forward, which has a shiny, modern metamask connector, and hopefully addresses these issues!

**Pull request closed without merging**
