### PR TITLE
Update authereum version

### PR DESCRIPTION
**Pull request by miguelmota**

### CODE REVIEW

**Comment by cwhinfrey** [comment]
@NoahZinsmeister I think the changes from #61 didn't make it into the `dist/`by the way.

**Comment by NoahZinsmeister** [comment]
ah, ok thanks! re-publishing soon, i'll ping here when it's done.

**Comment by NoahZinsmeister** [comment]
published as `@web3-react/core@6.0.6`

**Comment by cwhinfrey** [comment]
Thanks! @NoahZinsmeister

**Pull request merged**
