### PR TITLE
Update WalletConnect connector

### PR DESCRIPTION
**Pull request by pedrouid**
Changelog:
* remove error where rpc map can only have a single key
* update WalletConnect web3-provider package to 1.4.0

### CODE REVIEW

**Comment by shayelbaz1** [comment]
Get this error on npm start:

```
./node_modules/@web3-react/walletconnect-connector/dist/walletconnect-connector.esm.js 230:33
Module parse failed: Unexpected token (230:33)
You may need an appropriate loader to handle this file type.
|       var _temp6 = function () {
|         if (!_this4.walletConnectProvider) {
>           return Promise.resolve(import('@walletconnect/web3-provider').then(function (m) {
|             var _m$default;
|
```



Need help?

**Comment by anxolin** [comment]
Hei @pedrouid, I also did a PR motivated for that restriction in the networks that can be used. 

I also expose the whole parametrization from wallet connect. Let me know if my PR supersedes this one  #185

**Comment by pedrouid** [comment]
Awesome! @anxolin 🙌 

That PR #185 also looks really good

What do you think @NoahZinsmeister ?

**Comment by NoahZinsmeister** [comment]
merged #185 , will make sure it works before cutting a new release!

**Pull request closed without merging**
