### PR TITLE
Update wallet connect to 1.0.8

### PR DESCRIPTION
**Pull request by kimpers**
This updates `@walletconnect/web3-provider` to `1.0.8` to enable the awesome new mobile deep-linking feature.

### CODE REVIEW

**Comment by NoahZinsmeister** [comment]
blocked by a bug: https://codesandbox.io/s/elegant-cherry-5yf0t?file=/src/App.tsx:0-858

**Comment by mirshko** [comment]
is @pedrouid aware of this? @NoahZinsmeister

**Comment by pedrouid** [comment]
If this was related to the mismatched payoad id's then it should be fixed with 1.0.7

**Comment by kimpers** [comment]
> If this was related to the mismatched payoad id's then it should be fixed with 1.0.7

Thanks @pedrouid, I'll verify if the issue is fixed

**Comment by kimpers** [comment]
@NoahZinsmeister I've updated to the newly published `1.0.8` version, it has fixed this issue. See https://codesandbox.io/s/kind-forest-dw7xp

**Comment by NoahZinsmeister** [comment]
looks great, thanks a lot @kimpers (and @pedrouid )

pushed up a few small changes, will wait for CI to pass, then merge + release!

**Pull request merged**
