### PR TITLE
Add bsc-connector

### PR DESCRIPTION
**Pull request by ackratos**
add a new provider for binance chain wallet: https://chrome.google.com/webstore/detail/binance-chain-wallet/fhbohimaelbohpjbbldcngcnapndodjp?hl=en-US

The API document for binance chain wallet is here: https://docs.binance.org/smart-chain/wallet/wallet_api.html

**UPDATE**

To whom interested in integrating with Binance Chain Wallet, please check out this temporary fork: https://www.npmjs.com/package/@binance-chain/bsc-connector

### CODE REVIEW

**Comment by ackratos** [comment]
@NoahZinsmeister would you like review&merge this PR? Thanks a lot:)

**Comment by slwzero** [comment]
Hi, @NoahZinsmeister 

Our project is using web3 to build features. This Pr can help us solve the thing. Really really need your help about reviewing and merging this pr.

Many thanks!

**Comment by ackratos** [comment]
> Hi, @NoahZinsmeister
> 
> Our project is using web3 to build features. This Pr can help us solve the thing. Really really need your help about reviewing and merging this pr.
> 
> Many thanks!

please try this: To whom interested in integrating with Binance Chain Wallet, please check out this temporary fork: https://www.npmjs.com/package/@binance-chain/web3-connector

**Comment by itxtoledo** [comment]
why hasn't that been merged yet?

**Comment by NoahZinsmeister** [comment]
happy you've published a connector that seems to be working! going to pass on merging this, as i'd like to keep web3-react ethereum-first, but appreciate the effort, and of course your connector will continue to work.

**Comment by amirmamaghani** [comment]
So guys is the BSC-connector implemented and merged into web3-react? Thanks

**Pull request closed without merging**
