### PR TITLE
Update network-connector to specify POST Content-Type header

### LINKED ISSUE #173: network connector's fetch should specify Content-Type header
When connecting to a geth rpc endpoint (in this case L2 optimism) with the network connector, an error code 415 is received saying that the request payload must be 'application/json'

We can add the request header to the following line of the network-connector:

https://github.com/NoahZinsmeister/web3-react/blob/d0b038c748a42ec85641a307e6c588546d86afc2/packages/network-connector/src/index.ts#L63

Could add 

```js
        headers: {
          'Content-Type': 'application/json'
        },
```

Submitted a PR!

### PR DESCRIPTION
**Pull request by wildmolasses**
Resolves #173

### CODE REVIEW

**Comment by dmihal** [comment]
+1 this, this header is needed for the Arbitrum RPC endpoint

**Comment by mahpah** [comment]
polygon need this header, too

**Comment by mnill** [comment]
+1 BSC Nodes need this header.

**Comment by Velenir** [comment]
+10 for Avalanche

**Comment by burnto** [comment]
+1 needed for fantom

**Comment by zbronstein** [comment]
+1 needed for Endaoment

**Comment by tonyto** [comment]
+1 :-)

**Comment by Venoox** [comment]
+1

**Comment by CasperGhostCrypto** [comment]
+1 for cronos

**Pull request merged**
