### PR TITLE
Add protocol for connecting with MEW mobile

### PR DESCRIPTION
**Pull request by SteveMieskoski**
Great work with this guys.  This is an asset to the community.  We recently released our mobile app MEW mobile for iOS and Android. This PR adds the MEW connect protocol the mobile app uses to communicate between the application and the web.  

Please let me know if any changes are needed.  The one thing I didn't do was try to publish '@web3-react/mewconnect-connector' to npm.

### CODE REVIEW

**Comment by kvhnuke** [comment]
@NoahZinsmeister any update on this?

**Comment by RabbitDoge** [comment]
Any update on the integration ?

**Review by kasperwiese8 — APPROVED** [review]
Ja self

**Comment by Chef-Chungus** [comment]
@kasperwiese8 - Can we please merge this? It's been approved for quite some time and we would like to add MEW support to our site.

**Comment by SteveMieskoski** [comment]
Will be creating a new PR for this.

**Review by FeliciaAKelley — APPROVED** [review]

**Review by ttloves2 — COMMENTED** [review]
Is this right

**Pull request closed without merging**
