### PR TITLE
feat: add matic (polygon) to Portis Connector

### PR DESCRIPTION
**Pull request by quagliero**
Portis support matic (https://docs.portis.io/#/configuration?id=network) so this just allows it to connect without throwing an invariant error.

### CODE REVIEW

**Comment by ArlindoTorres** [comment]
I was about to create the same PR 😅 
Any reason not to merge this @NoahZinsmeister?

**Comment by LarryRyan0824** [comment]
Since there is already a PR, I changed up the list a little to follow order, and also got rid of the deprecated Matic chains. This list includes Mumbai which is the main testnet now.

```
var chainIdToNetwork = {
  1: 'mainnet',
  3: 'ropsten',
  4: 'rinkeby',
  5: 'goerli',
  8: 'ubiq',
  18: 'thundercoreTestnet',
  30: 'orchid',
  31: 'orchidTestnet',
  42: 'kovan',
  61: 'classic',
  77: 'sokol',
  99: 'core',
  100: 'xdai',
  108: 'thundercore',
  122: 'fuse',
  163: 'lightstreams',
  137: 'matic',
  80001: 'maticMumbai'
};
```

**Comment by RAMTO** [comment]
Yep, I need this as well, please :)

**Comment by radinat** [comment]
A merge would be great 🙏

**Comment by DimitarTAtanasov** [comment]
Would be great appreciated merging this PR, thanks.

**Comment by LarryRyan0824** [comment]
The test net is now Mumbai which is 80001. This needs to be changed before the merge.

**Comment by quagliero** [comment]
Updated, but can't see what is causing build to fail. All works fine locally.

**Comment by ochikov** [comment]
Anybody ?

**Comment by LarryRyan0824** [comment]
If you guys need matic in production, this is what I did.

- Go into the portis-connector.esm.js file and replace the chainIdToNetwork variable with
-`var chainIdToNetwork = {
  1: 'mainnet',
  3: 'ropsten',
  4: 'rinkeby',
  5: 'goerli',
  8: 'ubiq',
  18: 'thundercoreTestnet',
  30: 'orchid',
  31: 'orchidTestnet',
  42: 'kovan',
  61: 'classic',
  77: 'sokol',
  99: 'core',
  100: 'xdai',
  108: 'thundercore',
  122: 'fuse',
  163: 'lightstreams',
  137: 'matic',
  80001: 'maticMumbai'
};`
- Go to the console and cd into your project
- Enter `npx patch-package @web3-react/portis-connector`
- You will now have a "patches" folder made for your in your root folder with your changes
- Go into your package.json, and enter `"postinstall": "npx patch-package"` in your scripts
- `"scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject",
        "postinstall": "npx patch-package"
    },`
That will auto patch the Portis connector on start/build

**Comment by NoahZinsmeister** [comment]
added in https://github.com/NoahZinsmeister/web3-react/commit/117730f062de482c39c0c87112cc5f59bbff0147

**Pull request closed without merging**
