### PR TITLE
#476

### PR DESCRIPTION
**Pull request by NoahZinsmeister**
Fixes build issues from #476

### CODE REVIEW

**Comment by NoahZinsmeister** [comment]
cc @agcty , this branch removes the need for esbuild and cleans up all the other build issues.

also, you'll see that i'm now rendering all `usePriority*` hooks and storing the values in the context - this approach seems a little cleaner and more modular to me, what do you think?

**Comment by agcty** [comment]
yes much cleaner and more modular, also like that it's more explicit now! 

i just couldn't get it working with tsc for some reason, that's why I used esbuild! not sure what the "best" build tool nowadays is but esbuild seemed pretty easy to set up, and is just really fast, guess the library doesn't really need esbuild but if you ever wanted to use it for some reason the esbuild2 branch on my repo now supports watching as well 😅

**Comment by agcty** [comment]
also, do you have any setup to instantly have the packages update in example-next? was looking for a way but couldn't find one

**Comment by NoahZinsmeister** [comment]
appreciate that! yeah i went through esm/cjs dual build hell for a while and it was not worth it, so trying to stick to vanilla cjs via tsc, but good to have another data point

re. updating: as long as the `@web3-react/*` package versions in the package.json of example-next match the versions in the actual packages, lerna will link them and `yarn start` should start compilation for all sibling packages in watch mode alongside the example, and changes should be instantly reflected in localhost:3000

**Pull request merged**
